# Generated by Django 5.1.3 on 2024-12-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('free', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='Нет описания', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
