# Generated by Django 5.1.3 on 2024-12-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_community_rename_title_post_name_remove_post_body_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Community',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='free',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='РќРµС‚ РѕРїРёСЃР°РЅРёСЏ'),
            preserve_default=False,
        ),
    ]
